In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df=pd.read_csv('Advertising.csv')
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [43]:
X=df.drop(columns='sales')
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [42]:
y=df['sales']
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [6]:
from sklearn.preprocessing import PolynomialFeatures
poly_convert= PolynomialFeatures(degree=3,include_bias=False)
poly_features=poly_convert.fit_transform(X)

In [7]:
poly_features.shape

(200, 19)

In [8]:
#normal train_testsplit
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(poly_features,y,test_size=0.3, random_state=101)

In [9]:
X_train.shape

(140, 19)

In [10]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(X_train)
scaled_xtrain= scaler.transform(X_train)
scaled_xtest=scaler.transform(X_test)

In [11]:
# the values have been restricted or scaled down between zero to one
scaled_xtrain

array([[ 0.49300171, -0.33994238,  1.61586707, ..., -0.16360242,
         0.54694754,  1.37075536],
       [ 1.61337153,  1.32852213,  1.90079242, ...,  2.63236858,
         2.6297449 ,  1.95593378],
       [-0.84811893, -1.58789957, -1.02319564, ..., -0.72634944,
        -0.61593941, -0.54133745],
       ...,
       [ 1.04606563, -1.30982215,  0.27064572, ..., -0.71065643,
        -0.53420112, -0.20690952],
       [ 0.74817069,  0.03987068, -1.26608283, ..., -0.66805936,
        -0.61031703, -0.54616941],
       [ 0.13813882,  0.55533126,  1.01799092, ...,  0.61006767,
         0.67881488,  0.45425942]])

In [12]:
from sklearn.linear_model import Ridge
ridge_model= Ridge(alpha=10)
ridge_model.fit(scaled_xtrain,y_train)
ycap=ridge_model.predict(scaled_xtest)

In [13]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
MAE= mean_absolute_error(y_test,ycap)
RMSE=np.sqrt(mean_squared_error(y_test,ycap))

In [14]:
MAE

0.5774404204714177

In [15]:
RMSE

0.894638646131968

In [16]:
from sklearn.linear_model import RidgeCV
#performs leave one out cross validation
ridge_cv= RidgeCV(alphas=(0.1, 1.0, 10.0),scoring='neg_mean_absolute_error')
ridge_cv.fit(scaled_xtrain,y_train)
ycap= ridge_cv.predict(scaled_xtest)
ycap

array([14.25006161, 19.10205204, 12.44776087, 17.07029103,  7.93609517,
        7.10314552, 19.94990664, 17.24524365, 10.33548736, 19.85951926,
        9.37933062, 13.9569529 , 11.85445773, 23.29303451, 19.30247423,
        9.42431717, 12.42484839,  9.21704461,  8.70229329, 21.42382243,
        7.14698141, 19.35684761, 27.33199316, 24.44887898,  9.23720121,
       11.46268721, 20.47427125,  9.4597969 , 12.55070677,  8.39250566,
        8.7928193 , 19.92435249, 10.8069225 ,  7.10760344, 18.16473242,
        9.30970124, 10.54163577,  9.71377387,  7.31109512, 10.76826686,
       12.32939318, 10.34155545, 11.39134453,  7.74592784, 11.73219215,
       10.60945023,  5.74446924, 15.33163484, 13.01377062, 22.65350817,
       10.59700761, 12.94758932, 14.71822795, 12.01718014, 11.35600126,
        5.47860188, 24.96469385,  9.42600079, 17.27904849, 15.59419989])

In [17]:
from sklearn.metrics import SCORERS
SCORERS

{'explained_variance': make_scorer(explained_variance_score),
 'r2': make_scorer(r2_score),
 'max_error': make_scorer(max_error, greater_is_better=False),
 'neg_median_absolute_error': make_scorer(median_absolute_error, greater_is_better=False),
 'neg_mean_absolute_error': make_scorer(mean_absolute_error, greater_is_better=False),
 'neg_mean_absolute_percentage_error': make_scorer(mean_absolute_percentage_error, greater_is_better=False),
 'neg_mean_squared_error': make_scorer(mean_squared_error, greater_is_better=False),
 'neg_mean_squared_log_error': make_scorer(mean_squared_log_error, greater_is_better=False),
 'neg_root_mean_squared_error': make_scorer(mean_squared_error, greater_is_better=False, squared=False),
 'neg_mean_poisson_deviance': make_scorer(mean_poisson_deviance, greater_is_better=False),
 'neg_mean_gamma_deviance': make_scorer(mean_gamma_deviance, greater_is_better=False),
 'accuracy': make_scorer(accuracy_score),
 'top_k_accuracy': make_scorer(top_k_accuracy_score, ne

In [18]:
ridge_cv.alpha_

0.1

In [19]:
new_MAE= mean_absolute_error(y_test,ycap)
new_MAE

0.427377488435646

In [20]:
new_RMS= np.sqrt(mean_squared_error(y_test,ycap))
new_RMS

0.6180719926949467

In [21]:
ridge_cv.coef_

array([ 5.40769392,  0.5885865 ,  0.40390395, -6.18263924,  4.59607939,
       -1.18789654, -1.15200458,  0.57837796, -0.1261586 ,  2.5569777 ,
       -1.38900471,  0.86059434,  0.72219553, -0.26129256,  0.17870787,
        0.44353612, -0.21362436, -0.04622473, -0.06441449])

In [22]:
from sklearn.linear_model import LassoCV

In [23]:
lasso_cv_model= LassoCV(eps=0.01,n_alphas=100,max_iter=100000)

In [24]:
lasso_cv_model.fit(scaled_xtrain,y_train)

LassoCV(eps=0.01, max_iter=100000)

In [25]:
lass_ycap=lasso_cv_model.predict(scaled_xtest)
lass_ycap

array([13.57320376, 19.48795875, 11.95274135, 16.19993212,  8.57669998,
        7.6071029 , 20.32747483, 17.42500968, 10.31986639, 20.03876934,
        9.87558333, 13.9183515 , 12.02703782, 23.05703864, 19.37820261,
        9.42037787, 12.32992062,  9.18161493,  8.68162248, 21.60807377,
        7.76619176, 18.98770792, 27.51910431, 24.76835785,  9.20756175,
       11.66883827, 20.77530248,  9.11890477, 12.49173309,  8.71612151,
        8.73778042, 20.10406056, 10.6935785 ,  7.34734505, 17.95145685,
        9.2349257 , 10.16830989,  9.57273112,  7.92101583, 10.79343988,
       11.95807534, 10.33989021, 10.90104803,  7.83414939, 11.28821578,
       10.28794429,  7.24071139, 15.53011283, 13.10398512, 22.38466178,
       10.37515748, 13.10639991, 14.56000763, 11.69298701, 11.54374986,
        6.79644083, 25.23970777, 10.01700991, 17.58510691, 15.4697173 ])

In [26]:
MAE=mean_absolute_error(y_test,lass_ycap)
MAE

0.5159788188265407

In [27]:
RMSE= np.sqrt(mean_squared_error(y_test,lass_ycap))
RMSE

0.7615440303260839

In [28]:
lasso_cv_model.coef_

array([ 2.35600233,  0.21183181,  0.        , -0.        ,  3.78675114,
       -0.        ,  0.        ,  0.0624318 ,  0.        , -1.01152151,
       -0.        , -0.        ,  0.        ,  0.        , -0.        ,
        0.        ,  0.        ,  0.        ,  0.        ])

In [29]:
from sklearn.linear_model import ElasticNetCV

In [30]:
elastic_model= ElasticNetCV(l1_ratio=[.1, .5, .7,.9, .95, .99, 1],eps=0.001,n_alphas=100,max_iter=1000000)

In [32]:
elastic_model.fit(scaled_xtrain,y_train)
elast_ycap= elastic_model.predict(scaled_xtest)
elast_ycap 

array([14.16203485, 19.2942685 , 12.34178429, 16.97745571,  8.02340978,
        6.95799942, 20.11875833, 17.32880647, 10.43139937, 19.96174466,
        9.56959473, 13.94205676, 11.90851817, 23.35138146, 19.56656277,
        9.27838151, 12.30485359,  9.30152997,  8.56733436, 21.51633564,
        7.06650884, 19.3377222 , 27.28027149, 24.52239173,  9.17172464,
       11.60918126, 20.73841405,  9.29953525, 12.56948515,  8.40051066,
        8.56984613, 20.03587647, 10.83439653,  6.79505173, 18.18820331,
        9.48107219, 10.41803957,  9.70785725,  7.22932328, 10.85467692,
       12.85491418, 10.51648453, 11.26905127,  7.41516944, 11.54705407,
       10.42233031,  6.02782344, 15.36338733, 13.18723611, 22.67619584,
       10.4721906 , 13.01165791, 14.56684361, 11.90062303, 11.47303307,
        5.59404766, 25.06115365,  9.69468957, 17.44771723, 15.60375637])

In [34]:
elastic_model.l1_ratio_

1.0

In [36]:
elastic_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [39]:
elastic_model.alpha_

0.004943070909225827

In [40]:
mean_absolute_error(elast_ycap,y_test)

0.4335034618590073

In [41]:
np.sqrt(mean_squared_error(elast_ycap,y_test))

0.6063140748984043